// SPDX-FileCopyrightText: 2026 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

import { ListView } from "std-widgets.slint";
import { Button } from "./button.slint";
import { BackupListLogic } from "../logic/backup_list.slint";
import { ThemeLogic } from "../logic/theme.slint";

export component BackupListDialog inherits Rectangle {
  background: rgba(0, 0, 0, 0.5);

  TouchArea {
    scroll-event => { accept } // Prevent scroll events being passed to the game screen
    clicked => BackupListLogic.cancel();
  }

  Rectangle {
    width: 480px;
    height: 420px;
    background: ThemeLogic.colors.surface;
    border-radius: 8px;

    VerticalLayout {
      padding: 24px;
      spacing: 16px;

      StyledText {
        text: @markdown("**<font color='\{ThemeLogic.colors.text_primary}'>\{@tr("Restore")}</font> <font color='\{ThemeLogic.colors.text_secondary}'>\{BackupListLogic.game_name}</font>**");
        default-font-size: 18px;
      }

      Rectangle {
        border-color: ThemeLogic.colors.border_hover;
        border-width: 1px;
        border-radius: 6px;
        clip: true;

        ListView {
          vertical-scrollbar-policy: always-off;

          accessible-role: list;
          accessible-orientation: vertical;
          accessible-item-count: BackupListLogic.backups.length;

          for backup in BackupListLogic.backups: VerticalLayout {
            Rectangle {
              background: (entry_touch.has-hover || restore_btn.hovered) ? ThemeLogic.colors.surface_hover : transparent;

              entry_touch := TouchArea {}

              HorizontalLayout {
                padding: 10px;

                VerticalLayout {
                  alignment: center;

                  Text {
                    text: backup.timestamp;
                    color: ThemeLogic.colors.text_primary;
                    font-size: 14px;
                    font-weight: 400;
                  }

                  Text {
                    text: backup.size;
                    color: ThemeLogic.colors.text_muted;
                    font-size: 12px;
                  }
                }

                restore_btn := Button {
                  text: @tr("Restore");
                  background: ThemeLogic.colors.secondary;
                  width: 90px;
                  height: 32px;
                  clicked => BackupListLogic.restore(backup.path);
                }
              }
            }

            Rectangle { height: 1px; background: ThemeLogic.colors.border_hover; }
          }
        }
      }

      HorizontalLayout {
        alignment: end;

        Button {
          text: @tr("Cancel");
          background: ThemeLogic.colors.secondary;
          width: 100px;
          height: 36px;
          clicked => BackupListLogic.cancel();
        }
      }
    }
  }
}
