[package]
name = "aletheia"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3
lto = true
strip = true

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"
