[package]
name = "aletheia"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"

[profile.release]
opt-level = 3
lto = true
strip = true

[dependencies]
anyhow = "1.0.98"
glob = "0.3.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"
sha2 = "0.10.8"
