// SPDX-FileCopyrightText: 2025-2026 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

import { Scrollable } from "../components/scrollable.slint";
import { Button } from "../components/button.slint";
import { CheckBox } from "../components/check_box.slint";
import { TextLabel } from "../components/text_label.slint";
import { Dropdown } from "../components/dropdown.slint";
import { NumberInput } from "../components/number_input.slint";
import { ThemeLogic } from "../logic/theme.slint";
import { DropdownOption } from "../structs/dropdown_option.slint";
import { Config } from "../structs/config.slint";

export global SettingsScreenLogic {
  in property <Config> config;
  in property <[DropdownOption]> steam_account_options;
  in property <bool> show_update_settings;
  in property <string> previous_save_dir;
  in property <string> previous_steam_account_id;
  in property <int> previous_max_backups;
  in property <bool> previous_check_for_updates: false;
  in property <bool> has_steam_accounts: steam_account_options.length > 0;
  out property <bool> dirty: config.save_dir != previous_save_dir ||
                               config.steam_account_id != previous_steam_account_id ||
                               config.max_backups != previous_max_backups ||
                               config.check_for_updates != previous_check_for_updates;
  callback browse();
  callback update_gamedb();
  callback save_config(Config);
}

component Section {
  in property <image> icon;
  in property <string> title;
  in property <bool> show_divider: true;

  VerticalLayout {
    spacing: 16px;

    if root.show_divider: Rectangle {
      height: 1px;
      background: ThemeLogic.colors.secondary_hover;
    }

    HorizontalLayout {
      spacing: 12px;

      Image {
        width: 24px;
        height: 24px;
        source: root.icon;
        colorize: ThemeLogic.colors.text_secondary;
      }

      Text {
        text: root.title;
        color: ThemeLogic.colors.text_secondary;
        font-size: 18px;
        font-weight: 600;
        vertical-alignment: center;
      }
    }

    VerticalLayout {
      spacing: 12px;
      padding-left: 36px;

      @children
    }
  }
}

export component Settings {
  width: 100%;
  height: 100%;

  VerticalLayout {
    Scrollable {
      VerticalLayout {
        spacing: 24px;
        padding: 24px;
        padding-bottom: 12px;
        alignment: start;

        Section {
          show_divider: false;
          icon: @image-url("../assets/folder.svg");
          title: @tr("Game Data Location");

          Text {
            text: @tr("Choose where your games will be saved");
            color: ThemeLogic.colors.text_tertiary;
            font-size: 14px;
          }

          HorizontalLayout {
            spacing: 8px;

            TextLabel {
              width: 400px;
              height: 36px;
              text: SettingsScreenLogic.config.save_dir;
            }

            Button {
              width: 100px;
              height: 36px;
              text: @tr("Browse");
              clicked => SettingsScreenLogic.browse();
            }
          }
        }

        if SettingsScreenLogic.has_steam_accounts: Section {
          z: 1; // Dropdown needs to render over other components.
          icon: @image-url("../assets/switch_account.svg");
          title: @tr("Steam Account");

          VerticalLayout {
            spacing: 4px;

            Text {
              text: @tr("Choose the Steam account for your games");
              color: ThemeLogic.colors.text_tertiary;
              font-size: 14px;
            }

            Text {
              text: @tr("Only affects games that save in the Steam userdata directory");
              color: ThemeLogic.colors.text_muted;
              opacity: 40%;
              font-size: 10px;
            }
          }

          Dropdown {
            width: 200px;
            height: 36px;
            placeholder: @tr("Select an account…");
            options: SettingsScreenLogic.steam_account_options;
            value <=> SettingsScreenLogic.config.steam_account_id;
          }
        }

        Section {
          icon: @image-url("../assets/database.svg");
          title: @tr("GameDB");

          Text {
            text: @tr("Download the latest copy of the GameDB");
            color: ThemeLogic.colors.text_tertiary;
            font-size: 14px;
          }

          Button {
            width: 140px;
            height: 36px;
            text: @tr("Update GameDB");
            clicked => SettingsScreenLogic.update_gamedb();
          }
        }

        Section {
          icon: @image-url("../assets/history.svg");
          title: @tr("Backup Retention");

          Text {
            text: @tr("How many backups to keep per game");
            color: ThemeLogic.colors.text_tertiary;
            font-size: 14px;
          }

          NumberInput {
            width: 50px;
            height: 36px;
            minimum: 1;
            maximum: 255;
            value <=> SettingsScreenLogic.config.max_backups;
          }
        }

        if SettingsScreenLogic.show_update_settings: Section {
          icon: @image-url("../assets/update.svg");
          title: @tr("Updates");

          Text {
            text: @tr("Configure automatic update checking");
            color: ThemeLogic.colors.text_tertiary;
            font-size: 14px;
          }

          HorizontalLayout {
            spacing: 8px;
            alignment: start;

            CheckBox {
              text: @tr("Check for updates automatically");
              enabled <=> SettingsScreenLogic.config.check_for_updates;
            }
          }
        }
      }
    }

    HorizontalLayout {
      padding: 24px;
      padding-top: 12px;
      alignment: end;

      Button {
        width: 120px;
        height: 36px;
        text: @tr("Save");
        enabled: SettingsScreenLogic.dirty;
        clicked => SettingsScreenLogic.save_config(SettingsScreenLogic.config);
      }
    }
  }
}
