name: Bug Report
description: Report a bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Provide a brief, clear description of the issue.
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: e.g., Windows 11, Ubuntu 24.04
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g., v1.2.3
    validations:
      required: true

  - type: input
    id: installation
    attributes:
      label: Installation Method
      placeholder: e.g., exe, AppImage, Flatpak
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      placeholder: Paste logs here
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates.
          required: true
        - label: I have provided all relevant information above.
          required: true
        - label: I can reproduce this issue consistently.
          required: true
        - label: I have checked that my game paths are accessible.
          required: true

