// SPDX-FileCopyrightText: 2025-2026 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

import { NotificationType } from "../components/notification.slint";

export global NotificationLogic {
  private property <bool> notification_visible;
  private property <string> notification_message;
  private property <NotificationType> notification_type: NotificationType.INFO;

  public function show_success(message: string) {
    show(message, NotificationType.SUCCESS);
  }

  public function show_error(message: string) {
    show(message, NotificationType.ERROR);
  }

  public function show_info(message: string) {
    show(message, NotificationType.INFO);
  }

  public function show_warning(message: string) {
    show(message, NotificationType.WARNING);
  }

  public function show_success_fmt(key: string, param: string) {
    show_fmt(key, param, NotificationType.SUCCESS);
  }

  // Unused for now
  // public function show_error_fmt(key: string, param: string) {
  //   show_fmt(key, param, NotificationType.ERROR);
  // }
  //
  // public function show_info_fmt(key: string, param: string) {
  //   show_fmt(key, param, NotificationType.INFO);
  // }
  //
  // public function show_warning_fmt(key: string, param: string) {
  //   show_fmt(key, param, NotificationType.WARNING);
  // }

  pure function translate(key: string) -> string {
    key == "STEAM_ACCOUNT_MISSING" ? @tr("Set your Steam account in settings")
      : key == "BACKUP_DIRECTORY_MISSING" ? @tr("Backup directory does not exist")
      : key == "SAVED_SETTINGS" ? @tr("Successfully saved settings")
      : key == "GAMEDB_UPDATED" ? @tr("Successfully updated GameDB")
      : key == "GAMEDB_UP_TO_DATE" ? @tr("GameDB is already up to date")
      : key == "GAMEDB_UPDATE_FAILED" ? @tr("Failed to update GameDB")
      : key == "ARCHIVE_CORRUPTED" ? @tr("Archive corrupted")
      : key == "INVALID_ARCHIVE" ? @tr("Invalid archive")
      : key == "IO_ERROR" ? @tr("I/O error")
      : key == "UNSUPPORTED_ARCHIVE_VERSION" ? @tr("Unsupported archive version")
      : key == "NO_BACKUPS_FOUND" ? @tr("No backups found")
      : key == "GAME_NOT_INSTALLED" ? @tr("Game is not installed")
      : key == "GAME_NAME_TOO_LONG" ? @tr("Game name is too long")
      : key
  }

  function translate_fmt(key: string, param: string) -> string {
    key == "BACKED_UP" ? @tr("Backed up {} games", param)
      : key == "RESTORED" ? @tr("Restored {} games", param)
      : key
  }

  function show(key: string, type: NotificationType) {
    notification_message = translate(key);
    notification_type = type;
    notification_visible = true;
  }

  function show_fmt(key: string, param: string, type: NotificationType) {
    notification_message = translate_fmt(key, param);
    notification_type = type;
    notification_visible = true;
  }

  public function hide_notification() {
    notification_visible = false;
  }

  out property <bool> is_notification_visible: notification_visible;
  out property <string> current_notification_message: notification_message;
  out property <NotificationType> current_notification_type: notification_type;
}
