// SPDX-FileCopyrightText: 2025-2026 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

import "./fonts/Inter/InterVariable.ttf";
import "./fonts/Inter/InterVariable-Italic.ttf";

import { BackupListDialog } from "./components/backup_list_dialog.slint";
import { NavItem } from "./components/nav_item.slint";
import { Notification } from "./components/notification.slint";
import { AppLogic } from "./logic/app.slint";
import { BackupListLogic } from "./logic/backup_list.slint";
import { FirstTimeSetup } from "./first_time_setup.slint";
import { GameLogic } from "./logic/game.slint";
import { NotificationLogic } from "./logic/notification.slint";
import { RestoreLogic } from "./logic/restore.slint";
import { UpdaterLogic } from "./logic/updater.slint";
import { About } from "./screens/about.slint";
import { Games, GamesScreenLogic } from "./screens/games.slint";
import { RestoreDialog } from "./restore_dialog.slint";
import { Settings, SettingsScreenLogic } from "./screens/settings.slint";
import { SetupLogic } from "./logic/setup.slint";
import { ThemeLogic } from "./logic/theme.slint";
import { Updater } from "./updater.slint";

export { AppLogic, BackupListLogic, GamesScreenLogic, GameLogic, NotificationLogic, SettingsScreenLogic }
export { FirstTimeSetup, SetupLogic }
export { RestoreDialog, RestoreLogic }
export { Updater, UpdaterLogic }

enum Screen {
  About,
  Games,
  Settings
}

export component App inherits Window {
  private property <Screen> current_screen: Screen.Games;

  default-font-family: "Inter Variable";
  preferred-width: 1280px;
  preferred-height: 900px;
  min-width: 650px;
  min-height: 500px;
  title: "Aletheia";
  icon: @image-url("../resources/logo/moe.spencer.Aletheia.png");
  background: ThemeLogic.colors.surface;

  VerticalLayout {
    HorizontalLayout {
      spacing: 16px;
      padding: 16px;

      accessible-role: tab-list;
      accessible-item-count: 3;

      NavItem {
        text: @tr("Games");
        icon: @image-url("./assets/joystick.svg");
        active: root.current_screen == Screen.Games;
        index: 0;
        clicked => {
          if (root.current_screen != Screen.Games) {
            GamesScreenLogic.filter(""); // Lazy hack to reset search, waiting for https://github.com/slint-ui/slint/pull/6657 to be merged.
          }

          root.current_screen = Screen.Games;
        }
      }

      NavItem {
        text: @tr("Settings");
        icon: @image-url("./assets/settings.svg");
        active: root.current_screen == Screen.Settings;
        index: 1;
        clicked => { root.current_screen = Screen.Settings }
      }

      NavItem {
        text: @tr("About");
        icon: @image-url("./assets/about.svg");
        active: root.current_screen == Screen.About;
        index: 2;
        clicked => { root.current_screen = Screen.About; }
      }
    }

    Rectangle {
      background: ThemeLogic.colors.background;
      border-radius: 8px;

      match root.current_screen {
        Games: Games {}
        Settings: Settings {}
        About: About {}
      }
    }
  }

  Notification {
    y: parent.height - self.height - 20px;
    target_x: parent.width - self.width - 20px;
    visible: NotificationLogic.is_notification_visible;
    message: NotificationLogic.current_notification_message;
    notification_type: NotificationLogic.current_notification_type;
    closed => NotificationLogic.hide_notification();
  }

  if BackupListLogic.visible: BackupListDialog {}
}
