// SPDX-FileCopyrightText: 2026 Spencer
// SPDX-License-Identifier: AGPL-3.0-only

import { Button } from "./components/button.slint";
import { RestoreLogic } from "./logic/restore.slint";
import { ThemeLogic } from "./logic/theme.slint";

export component RestoreDialog inherits Window {
  private property <bool> ok: RestoreLogic.error.is-empty;

  title: @tr("Aletheia - Restore backup");
  icon: @image-url("../resources/logo/moe.spencer.Aletheia.png");
  default-font-family: "Inter";
  width: 520px;
  height: 240px;
  background: ThemeLogic.colors.surface;

  VerticalLayout {
    padding: 24px;
    spacing: 16px;

    VerticalLayout {
      spacing: 6px;
      alignment: start;

      VerticalLayout {
        spacing: 2px;
        alignment: start;

        Text {
          text: @tr("Restore backup");
          color: ThemeLogic.colors.text_primary;
          font-size: 18px;
          font-weight: 600;
        }

        Text {
          color: ThemeLogic.colors.text_secondary;
          text: @tr("Are you sure you want to restore {}?", RestoreLogic.game_name);
          font-size: 14px;
        }
      }

      Text {
        text: RestoreLogic.timestamp;
        color: ThemeLogic.colors.text_tertiary;
        font-size: 12px;
      }
    }

    Rectangle {
      background: ok
                  ? ThemeLogic.colors.restore_dialog_info_warning
                  : ThemeLogic.colors.restore_dialog_info_error;

      border-radius: 8px;

      VerticalLayout {
        padding: 18px;

        HorizontalLayout {
          spacing: 12px;
          padding-left: 4px;

          Image {
            source: @image-url("assets/info.svg");
            colorize: ok ? ThemeLogic.colors.restore_dialog_icon_warning : ThemeLogic.colors.restore_dialog_icon_error;
            width: 18px;
            height: 18px;
          }

          Text {
            text: ok ? @tr("This will overwrite any existing save data.") : RestoreLogic.translate_error();
            color: ThemeLogic.colors.text_muted;
            font-size: 12px;
            wrap: word-wrap;
          }
        }
      }
    }

    HorizontalLayout {
      spacing: 12px;
      alignment: end;

      Button {
        text: ok ? @tr("Cancel") : @tr("Close");
        background: ThemeLogic.colors.secondary;
        width: 100px;
        height: 36px;
        clicked => root.hide();
      }

      if ok: Button {
        text: @tr("Restore");
        background: ThemeLogic.colors.primary;
        width: 100px;
        height: 36px;
        clicked => RestoreLogic.restore();
      }
    }
  }
}
