name: Lint GameDB
on:
  pull_request:
    paths:
      - 'resources/gamedb.yaml'

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install YAMLLint
        run: sudo apt update && sudo apt install -y yamllint

      - name: Lint GameDB
        run: |
          yamllint -d '{
            extends: "default",
            rules: {
              document-start: {enabled: false},
              line-length: {enabled: false},
              key-ordering: {enabled: true}
            }
          }' -f github -s resources/gamedb.yaml
